export enum ToastEventsEnum {
  'CLOSE_TOAST' = 'CLOSE_TOAST',
  'TRANSACTION_TOAST_DATA_UPDATE' = 'TRANSACTION_TOAST_DATA_UPDATE',
  'CUSTOM_TOAST_DATA_UPDATE' = 'CUSTOM_TOAST_DATA_UPDATE',
  'VIEW_ALL' = 'VIEW_ALL',
}
